# Generated by Django 4.2.27 on 2026-01-08 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('min_experience_years', models.IntegerField(default=0)),
                ('education_levels', models.JSONField(blank=True, default=list)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(blank=True, max_length=200)),
                ('candidate_email', models.EmailField(blank=True, max_length=254)),
                ('candidate_phone', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('linkedin_url', models.URLField(blank=True)),
                ('cv_file', models.FileField(upload_to='cvs/')),
                ('cv_text', models.TextField(blank=True)),
                ('score', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('tres_pertinent', 'Très pertinent'), ('pertinent', 'Pertinent'), ('a_revoir', 'À revoir'), ('peu_pertinent', 'Peu pertinent')], default='a_revoir', max_length=20)),
                ('exp_years', models.IntegerField(default=0)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('gaps', models.JSONField(blank=True, default=list)),
                ('is_shortlisted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('received', 'Received'), ('in_review', 'In review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='received', max_length=20)),
                ('feedback_reason', models.TextField(blank=True)),
                ('feedback_suggestions', models.TextField(blank=True)),
                ('status_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.job')),
            ],
        ),
    ]
