# Generated by Django 5.2.5 on 2026-01-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_application_current_stage_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='extra_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='job',
            name='apply_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='contract_type',
            field=models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('freelance', 'Freelance'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_sector',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
